#!/bin/bash
echo "Resetting plugin to default state..."
echo "-----------------------------------------------------------------"

BOOT="/boot/config/plugins/dwpython"
DOCROOT="/usr/local/emhttp/plugins/dwpython"

rm -rf /etc/dwpython/* >/dev/null 2>&1
rm -rf $BOOT/scripts/* >/dev/null 2>&1

if [ ! -d /etc/dwpython ]; then
    mkdir -p /etc/dwpython >/dev/null 2>&1
fi

if [ ! -d $BOOT/scripts ]; then
    mkdir -p $BOOT/scripts >/dev/null 2>&1
fi

cp -f $DOCROOT/default.cfg $BOOT/dwpython.cfg >/dev/null 2>&1

cp -rf $DOCROOT/defaults/* $BOOT/scripts/ >/dev/null 2>&1

cp -rf $BOOT/scripts/* /etc/dwpython/ >/dev/null 2>&1

chmod 755 $DOCROOT/scripts/* >/dev/null 2>&1
chmod 755 /etc/dwpython/*.sh >/dev/null 2>&1

if [ "$( grep -ic "dwpython" /etc/rc.d/rc.local_shutdown )" -eq 0 ]; then
    sed -i -e '/# Get time-out setting/i [ -x /usr/local/emhttp/plugins/dwpython/scripts/backup ] && /usr/local/emhttp/plugins/dwpython/scripts/backup' -e //N /etc/rc.d/rc.local_shutdown
fi

echo "The operation has finished, you can close this window now."
echo "Installed packages were not touched, reboot to purge those from your system."
